name: rbig_jax
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
# Standard Libraries
- numpy            # Numerical Linear Algebra
- scipy             # Scientific Computing
- scikit-learn     # Machine Learning
- conda-forge::statsmodels
- scikit-image
# Plotting Libraries
- matplotlib        # standard plotting library
- seaborn          # Stats viz library
# GUI
- conda-forge::ipywidgets
- ipykernel
- conda-forge::tqdm
- conda-forge::jaxlib
- conda-forge::jax
- pip
- pip:
  # Jax framework
  - distrax
  - chex
  - optax
  - numpyro
  # - tensorflow-probability>=0.12.1
  - treex
  - treeo
  - elegy
  - einops
  # formatting
  - black
  - pylint
  - isort
  - flake8
  - mypy
  - pytest
  # Notebook stuff
  - pyprojroot
  # logging
  - wandb
  # plotting
  - seaborn
  - celluloid
  - corner
