name: rbig_jax_gpu
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
# Standard Libraries
- numpy>1.19
- scipy>1.5
- scikit-learn>0.23
- matplotlib>3.3
- pytorch::pytorch
- pytorch::torchvision
- pytorch::torchaudio
- conda-forge::cudatoolkit=10.2
- pip
- pip:
  # Jax framework
  - jax>=0.2.11
  - "jaxlib>=0.1.65+cuda102 -f https://storage.googleapis.com/jax-releases/jax_releases.html"
#   - "git+git://github.com/deepmind/chex.git"
#   - objax
#   - numpyro
#   - distrax
#   - tfp-nightly
#   - chex
#   # PyTorch
#   - pytorch-lightning>=1.2
#   - lightning-bolts>=0.3
#   # formatting
#   - black
#   - isort
#   - mypy
#   - pytest
#   # Notebook stuff
#   - ipykernel
#   - nb_black
#   - pyprojroot
#   # logging
#   - wandb
#   # plotting
#   - seaborn
#   - celluloid
#   - corner
