#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Gaussianization  # The title of the book. Will be placed in the left navbar.
author                      : IPL-UV  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
# logo                        : book.png  # A path to the book logo
execute:
  execute_notebooks: cache

repository:
  url                       : https://github.com/IPL-UV/rbig_jax  # Online location of your book
  path_to_book              : jupyterbook  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

html:
  use_repository_button: true
  only_build_toc_files: true
  extra_navbar: See the project in <a href="https://github.com/IPL-UV/rbig_jax">GitHub</a>

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""